// 打点页面及按钮规则
export default {
  // 项目需求一手房销售入口页面
  'HOME': 'BOO2',
  // 项目推荐页
  'PROJECT': 'P003',
  // 项目推荐图片
  'PROJECTIMG': 'B019',
  // 项目推荐按钮
  'PROJECTBTN': 'B020',
  // 求合作按钮确定
  'HEZUOBTNCONFIRM': 'B070',
  // 求合作按钮取消
  'HEZUOBTNCONCEL': 'B071',
  // 项目详情
  'PROJECTDETAIL': 'P017',
  // 项目详情按钮
  'PROJECTDETAILBTN': 'B020',
  // 项目详情分享按钮
  'PROJECTEXPORT': 'B062',
  // 项目分享页面
  'PROJECTEXPORTPAGE': 'P037',
  // 项目分享给朋友成功
  'PROJECTTOFRIEND': 'B065',
  // 项目分享给朋友失败
  'PROJECTTOFRIENDBAD': 'B066',
  // 项目分享到朋友圈成功
  'PROJECTTOCIRCLEOFFRIENDS': 'B067',
  // 项目分享到朋友圈失败
  'PROJECTTOCIRCLEOFFRIENDSBAD': 'B068',
  // 我要报备页面
  'BAOBEIPAGE': 'P018',
  // 海外房产
  'OVERSEAS': 'B121',
  // 海外房产页
  'OVERSEASPAGE': 'P049',
  // 海外房产报备按钮
  'OVERSEASBTN': 'B020',
  // 海外房产图片
  'OVERSEASIMG': 'B019',
  // 海外房产详情页
  'OVERSEASXPAGE': 'P050',
  // 海外房产分享按钮
  'OVERSEASHARE': 'B062',
  // 海外房产导出页面
  'OVERSEASEXPORT': 'P051',
  // 平台消息页面1
  'SWIPERDETAIL1': 'G001',
  // 平台消息页面2
  'SWIPERDETAIL2': 'G002'
}
